import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:image_picker/image_picker.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:flutter/foundation.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/widgets/florence_loader.dart';
import '../../../data/models/book_model.dart';
import '../../../data/models/memo_model.dart';
import '../../library/providers/book_providers.dart';
import '../providers/memo_providers.dart';
import 'dart:convert';

class AddPhotoMemoScreen extends ConsumerStatefulWidget {
  final String isbn;
  final Book? book;

  const AddPhotoMemoScreen({super.key, required this.isbn, this.book});

  @override
  ConsumerState<AddPhotoMemoScreen> createState() => _AddPhotoMemoScreenState();
}

class _AddPhotoMemoScreenState extends ConsumerState<AddPhotoMemoScreen> {
  final TextEditingController _pageController = TextEditingController();
  bool _isProcessing = false;
  XFile? _selectedImage;
  Uint8List? _previewBytes;
  final ImagePicker _picker = ImagePicker();

  @override
  void dispose() {
    _pageController.dispose();
    super.dispose();
  }

  void _showImageSourceActionSheet() {
    showModalBottomSheet(
      context: context,
      backgroundColor: Colors.transparent,
      builder: (BuildContext context) {
        return Container(
          decoration: const BoxDecoration(
            color: AppColors.ivory,
            borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
          ),
          child: SafeArea(
            child: Wrap(
              children: [
                const Padding(
                  padding: EdgeInsets.symmetric(vertical: 16.0),
                  child: Center(
                    child: Text(
                      '사진 추가 방식 선택',
                      style: TextStyle(
                        fontWeight: FontWeight.bold,
                        fontSize: 16,
                      ),
                    ),
                  ),
                ),
                ListTile(
                  leading: const Icon(Icons.camera_alt, color: AppColors.black),
                  title: const Text('카메라로 바로 촬영'),
                  onTap: () {
                    context.pop();
                    _pickImage(ImageSource.camera);
                  },
                ),
                ListTile(
                  leading: const Icon(Icons.photo_library, color: AppColors.black),
                  title: const Text('갤러리에서 선택'),
                  onTap: () {
                    context.pop();
                    _pickImage(ImageSource.gallery);
                  },
                ),
              ],
            ),
          ),
        );
      },
    );
  }

  Future<void> _pickImage(ImageSource source) async {
    try {
      final XFile? image = await _picker.pickImage(source: source);
      if (image == null) return;

      final bytes = await image.readAsBytes();
      setState(() {
        _selectedImage = image;
        _previewBytes = bytes;
      });
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('사진 가져오기 실패: $e')),
        );
      }
    }
  }

  Future<void> _savePhotoMemo() async {
    if (_selectedImage == null) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(const SnackBar(content: Text('먼저 사진을 추가해주세요.')));
      return;
    }

    setState(() => _isProcessing = true);

    try {
      final userId = Supabase.instance.client.auth.currentUser?.id;
      if (userId == null) throw Exception('User not logged in');

      String? imageUrl = await ref
          .read(supabaseRepositoryProvider)
          .uploadMemoImage(userId, _selectedImage!);

      // Empty text delta since this is a photo-only memo
      final jsonDelta = '[{"insert":"\\n"}]';

      final memo = Memo(
        id: '', // Generated by DB
        userId: userId,
        isbn: widget.isbn,
        content: jsonDelta,
        imageUrl: imageUrl,
        pageNumber: int.tryParse(_pageController.text),
        createdAt: DateTime.now(),
      );

      await ref.read(supabaseRepositoryProvider).saveMemo(memo);

      ref.invalidate(memosProvider(widget.isbn));

      if (mounted) {
        context.pop();
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(const SnackBar(content: Text('사진이 저장되었습니다.')));
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('저장 실패: $e')));
      }
    } finally {
      if (mounted) setState(() => _isProcessing = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.ivory,
      appBar: AppBar(
        backgroundColor: AppColors.ivory,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.close, color: AppColors.black),
          onPressed: () => context.pop(),
        ),
        title: Text(
          '사진 추가',
          style: Theme.of(context).textTheme.titleMedium?.copyWith(
            fontWeight: FontWeight.bold,
            color: AppColors.black,
          ),
        ),
        actions: [
          TextButton(
            onPressed: _isProcessing ? null : _savePhotoMemo,
            child: _isProcessing
                ? const SizedBox(
                    width: 24,
                    height: 16,
                    child: FlorenceLoader(width: 24, height: 16),
                  )
                : Text(
                    '저장',
                    style: Theme.of(context).textTheme.labelLarge?.copyWith(
                      color: AppColors.burgundy,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
          ),
        ],
      ),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Column(
            children: [
              // Book Info (Brief)
              if (widget.book != null)
                Row(
                  children: [
                    Container(
                      width: 40,
                      height: 60,
                      decoration: BoxDecoration(
                        color: AppColors.greyLight,
                        borderRadius: BorderRadius.circular(4),
                        image: DecorationImage(
                          image: NetworkImage(widget.book!.coverUrl),
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: Text(
                        widget.book!.title,
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                        style: const TextStyle(
                          fontWeight: FontWeight.bold,
                          color: AppColors.grey,
                        ),
                      ),
                    ),
                  ],
                ),
              if (widget.book != null) const SizedBox(height: 24),

              // Page Input
              Row(
                children: [
                  const Icon(Icons.menu_book, size: 20, color: AppColors.grey),
                  const SizedBox(width: 8),
                  Expanded(
                    child: TextField(
                      controller: _pageController,
                      keyboardType: TextInputType.number,
                      decoration: const InputDecoration(
                        hintText: '페이지를 입력해주세요 (선택사항)',
                        border: InputBorder.none,
                        isDense: true,
                      ),
                    ),
                  ),
                ],
              ),
              const Divider(),
              const SizedBox(height: 16),

              // Large Image Preview / Picker
              Expanded(
                child: GestureDetector(
                  onTap: _showImageSourceActionSheet,
                  child: Container(
                    width: double.infinity,
                    decoration: BoxDecoration(
                      color: _previewBytes != null
                          ? Colors.transparent
                          : Colors.grey.withOpacity(0.1),
                      borderRadius: BorderRadius.circular(16),
                      border: _previewBytes != null
                          ? null
                          : Border.all(color: Colors.grey.withOpacity(0.3), width: 2),
                      image: _previewBytes != null
                          ? DecorationImage(
                              image: MemoryImage(_previewBytes!),
                              fit: BoxFit.contain, // Show full photo
                            )
                          : null,
                    ),
                    child: _previewBytes == null
                        ? Column(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              Icon(
                                Icons.add_a_photo_outlined,
                                size: 48,
                                color: Colors.grey.withOpacity(0.8),
                              ),
                              const SizedBox(height: 16),
                              Text(
                                '터치하여 사진을 추가하세요',
                                style: TextStyle(
                                  color: Colors.grey.withOpacity(0.8),
                                  fontWeight: FontWeight.bold,
                                ),
                              ),
                              const SizedBox(height: 8),
                              Text(
                                '카메라 촬영 또는 갤러리 선택 가능',
                                style: TextStyle(
                                  color: Colors.grey.withOpacity(0.6),
                                  fontSize: 12,
                                ),
                              ),
                            ],
                          )
                        : Stack(
                            children: [
                              Positioned(
                                right: 16,
                                bottom: 16,
                                child: Container(
                                  padding: const EdgeInsets.symmetric(
                                      horizontal: 16, vertical: 8),
                                  decoration: BoxDecoration(
                                    color: Colors.black.withOpacity(0.6),
                                    borderRadius: BorderRadius.circular(20),
                                  ),
                                  child: const Text(
                                    '다시 선택하려면 터치',
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 12,
                                      fontWeight: FontWeight.bold,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
