import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:image_picker/image_picker.dart';
import 'package:google_mlkit_text_recognition/google_mlkit_text_recognition.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/widgets/florence_loader.dart';
import '../../../data/models/book_model.dart';
import '../../../data/models/memo_model.dart';
import 'dart:convert';
import 'package:flutter_quill/flutter_quill.dart' as quill;
import '../../library/providers/book_providers.dart';
import '../providers/memo_providers.dart';

class WriteMemoScreen extends ConsumerStatefulWidget {
  final String isbn;
  final Book? book;

  const WriteMemoScreen({
    super.key,
    required this.isbn,
    this.book,
  });

  @override
  ConsumerState<WriteMemoScreen> createState() => _WriteMemoScreenState();
}

class _WriteMemoScreenState extends ConsumerState<WriteMemoScreen> {
  final quill.QuillController _quillController = quill.QuillController.basic();
  final TextEditingController _pageController = TextEditingController();
  bool _isProcessing = false;
  XFile? _selectedImage;
  Uint8List? _previewBytes;

  final ImagePicker _picker = ImagePicker();

  @override
  void initState() {
    super.initState();
    final now = DateTime.now();
    final ampm = now.hour < 12 ? '오전' : '오후';
    final hour = now.hour > 12 ? now.hour - 12 : (now.hour == 0 ? 12 : now.hour);
    final dateStr = '${now.year}. ${now.month}. ${now.day}. $ampm $hour:${now.minute.toString().padLeft(2, '0')}\n\n';
    
    _quillController.document.insert(0, dateStr);
  }

  @override
  void dispose() {
    _quillController.dispose();
    _pageController.dispose();
    super.dispose();
  }

  Future<void> _pickImageAndExtractText() async {
    // Web does not support MLKit OCR
    if (kIsWeb) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('OCR(텍스트 추출) 기능은 모바일 앱에서만 지원됩니다.')),
      );
      return;
    }
  
    // Mobile Check (Runtime)
    if (defaultTargetPlatform != TargetPlatform.android && 
        defaultTargetPlatform != TargetPlatform.iOS) {
       ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('OCR 기능은 현재 모바일에서만 지원됩니다.')),
      );
      return;
    }

    try {
      final XFile? image = await _picker.pickImage(source: ImageSource.gallery);
      if (image == null) return;

      final bytes = await image.readAsBytes();

      setState(() {
        _selectedImage = image;
        _previewBytes = bytes;
        _isProcessing = true;
      });

      // NOTE: google_mlkit_text_recognition might allow import on web but fail at runtime.
      // If build fails here due to InputImage using File internally, we need a conditional import wrapper.
      // Assuming for now it compiles but throws at runtime if called.
      // We guarded with kIsWeb above.
      
      final inputImage = InputImage.fromFilePath(image.path);
      final textRecognizer = TextRecognizer(script: TextRecognitionScript.korean);
      final RecognizedText recognizedText = await textRecognizer.processImage(inputImage);

      if (mounted) {
        setState(() {
          final currentDocLength = _quillController.document.length;
          // insert before the trailing newline
          _quillController.document.insert(currentDocLength > 1 ? currentDocLength - 1 : 0, '\n${recognizedText.text}\n');
          _isProcessing = false;
        });
        
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('텍스트를 추출했습니다.')),
        );
      }
      
      textRecognizer.close();
    } catch (e) {
      if (mounted) {
        setState(() => _isProcessing = false);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('텍스트 추출 실패: $e')),
        );
      }
    }
  }

  Future<void> _saveMemo() async {
    if (_quillController.document.isEmpty() || _quillController.document.toPlainText().trim().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('내용을 입력해주세요.')),
      );
      return;
    }

    setState(() => _isProcessing = true);

    try {
      final userId = Supabase.instance.client.auth.currentUser?.id;
      if (userId == null) throw Exception('User not logged in');

      String? imageUrl;
      if (_selectedImage != null) {
        imageUrl = await ref
            .read(supabaseRepositoryProvider)
            .uploadMemoImage(userId, _selectedImage!);
      }
      
      final jsonDelta = jsonEncode(_quillController.document.toDelta().toJson());

      final memo = Memo(
        id: '', // Generated by DB
        userId: userId,
        isbn: widget.isbn,
        content: jsonDelta,
        imageUrl: imageUrl,
        pageNumber: int.tryParse(_pageController.text),
        createdAt: DateTime.now(),
      );

      await ref.read(supabaseRepositoryProvider).saveMemo(memo);
      
      ref.invalidate(memosProvider(widget.isbn));

      if (mounted) {
        context.pop();
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('메모가 저장되었습니다.')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('저장 실패: $e')),
        );
      }
    } finally {
      if (mounted) setState(() => _isProcessing = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.ivory,
      appBar: AppBar(
        backgroundColor: AppColors.ivory,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.close, color: AppColors.black),
          onPressed: () => context.pop(),
        ),
        title: Text(
          '메모 작성',
          style: Theme.of(context).textTheme.titleMedium?.copyWith(
                fontWeight: FontWeight.bold,
                color: AppColors.black,
              ),
        ),
        actions: [
          TextButton(
            onPressed: _isProcessing ? null : _saveMemo,
            child: _isProcessing
                ? const SizedBox(
                    width: 24,
                    height: 16,
                    child: FlorenceLoader(width: 24, height: 16),
                  )
                : Text(
                    '저장',
                    style: Theme.of(context).textTheme.labelLarge?.copyWith(
                          color: AppColors.burgundy,
                          fontWeight: FontWeight.bold,
                        ),
                  ),
          ),
        ],
      ),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Column(
            children: [
              // Book Info (Brief)
              if (widget.book != null)
                Row(
                  children: [
                     Container(
                       width: 40, 
                       height: 60,
                       decoration: BoxDecoration(
                         color: AppColors.greyLight,
                         borderRadius: BorderRadius.circular(4),
                         image: DecorationImage(
                           image: NetworkImage(widget.book!.coverUrl),
                           fit: BoxFit.cover,
                         ),
                       ),
                     ),
                     const SizedBox(width: 12),
                     Expanded(
                       child: Text(
                         widget.book!.title,
                         maxLines: 1,
                         overflow: TextOverflow.ellipsis,
                         style: const TextStyle(
                           fontWeight: FontWeight.bold,
                           color: AppColors.grey,
                         ),
                       ),
                     ),
                  ],
                ),
              if (widget.book != null) const SizedBox(height: 24),
              // Page Input
              Row(
                children: [
                  const Icon(Icons.menu_book, size: 20, color: AppColors.grey),
                  const SizedBox(width: 8),
                  Expanded(
                    child: TextField(
                      controller: _pageController,
                      keyboardType: TextInputType.number,
                      decoration: const InputDecoration(
                        hintText: '페이지를 입력해주세요',
                        border: InputBorder.none,
                        isDense: true,
                      ),
                    ),
                  ),
                ],
              ),
              const Divider(),
              // Image Preview
              if (_previewBytes != null)
                Container(
                  height: 200,
                  width: double.infinity,
                  margin: const EdgeInsets.only(bottom: 16),
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(12),
                    image: DecorationImage(
                      image: MemoryImage(_previewBytes!),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              // Content Input
              Expanded(
                child: quill.QuillEditor.basic(
                  controller: _quillController,
                  config: const quill.QuillEditorConfig(
                    placeholder: '기억하고 싶은 문장을 기록하세요...',
                    padding: EdgeInsets.all(8),
                  ),
                ),
              ),
              // Rich Text Toolbar above keyboard
              quill.QuillSimpleToolbar(
                controller: _quillController,
                config: const quill.QuillSimpleToolbarConfig(
                  showFontFamily: false,
                  showFontSize: false,
                  showSubscript: false,
                  showSuperscript: false,
                  showSearchButton: false,
                  showCodeBlock: false,
                  showInlineCode: false,
                  showBackgroundColorButton: false,
                  showClearFormat: false,
                  showAlignmentButtons: false,
                  showDirection: false,
                  showIndent: false,
                  showStrikeThrough: false,
                  showListCheck: false,
                  showLink: false,
                ),
              ),
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _pickImageAndExtractText,
        backgroundColor: AppColors.ivory, // Inverted for contrast
        foregroundColor: AppColors.burgundy,
        child: const Icon(Icons.camera_alt_outlined),
      ),
    );
  }
}
